language: node_js
node_js:
  - 10

install: npm install

jobs:
  include:
    - script: npm run lint
      name: "Lint"
    - script: npm run test:requesthandlers
      name: "Unit tests"

cache:
  directories:
    - node_modules

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
