language: node_js
node_js:
  - 10

install: npm install

jobs:
  include:
    - script: npm run lint
      name: "Lint"
    - script: npm run test:requesthandlers
      name: "Unit tests"

cache:
  directories:
    - node_modules
