version: '3'

services:
  frontend:
    build:
      context: frontend
      args:
        - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build: backend
    environment:
      - GENUS_CODICE_URL=genus-codice:5000
    env_file:
      - .env
    depends_on:
      - genus-codice
    container_name: backend
    restart: always

  proxy:
    build: proxy
    container_name: proxy
    restart: always

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/certs:/etc/ssl/certs
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
      - proxy
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  genus-codice:
    image: docker.pkg.github.com/sourcebin/genus-codice/genus-codice
    container_name: genus-codice
    restart: always
