version: '3'

services:
  frontend:
    build:
      context: frontend
      args:
        - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build: backend
    environment:
      - GENUS_CODICE_URL=genus-codice:5000
    env_file:
      - .env
    depends_on:
      - genus-codice
    container_name: backend
    restart: always

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/ssl
    depends_on:
      - frontend
      - backend
      - proxy
    container_name: nginx
    restart: always

  genus-codice:
    image: docker.pkg.github.com/sourcebin/genus-codice/genus-codice
    container_name: genus-codice
    restart: always

  proxy:
    image: docker.pkg.github.com/sourcebin/proxy/proxy:v0.0.3
    environment:
      - RUST_LOG=info
      - GENUS_CODICE_URL=genus-codice:5000
      - PROXY_SECRET=${PROXY_SECRET}
    container_name: proxy
    restart: always
