version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis
    depends_on:
      - redis
    container_name: app
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis
    depends_on:
      - redis
    container_name: api
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
